// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class KongaTestsTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() throws MalformedURLException {
    driver = new RemoteWebDriver(new URL("http://localhost:4444/wd/hub"), DesiredCapabilities.chrome());
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  public String waitForWindow(int timeout) {
    try {
      Thread.sleep(timeout);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    Set<String> whNow = driver.getWindowHandles();
    Set<String> whThen = (Set<String>) vars.get("window_handles");
    if (whNow.size() > whThen.size()) {
      whNow.removeAll(whThen);
    }
    return whNow.iterator().next();
  }
  @Test
  public void categories() {
    // Test name: categories
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("https://www.konga.com/");
    // 2 | setWindowSize | 1296x688 | 
    driver.manage().window().setSize(new Dimension(1296, 688));
    // 3 | click | linkText=All Categories | 
    driver.findElement(By.linkText("All Categories")).click();
    // 4 | mouseOver | css=.ba49d_JVzm4:nth-child(2) > a | 
    {
      WebElement element = driver.findElement(By.cssSelector(".ba49d_JVzm4:nth-child(2) > a"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 5 | mouseOver | css=.\_4730d_1wcu1 > a | 
    {
      WebElement element = driver.findElement(By.cssSelector(".\\_4730d_1wcu1 > a"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 6 | mouseOver | css=.\_4730d_1wcu1 > a | 
    {
      WebElement element = driver.findElement(By.cssSelector(".\\_4730d_1wcu1 > a"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 7 | click | css=.b6c6f_2H5Pm | 
    driver.findElement(By.cssSelector(".b6c6f_2H5Pm")).click();
    // 8 | close |  | 
    driver.close();
  }
  @Test
  public void selectingitemintocart() {
    // Test name: Selecting item into cart
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("https://www.konga.com/");
    // 2 | setWindowSize | 1296x688 | 
    driver.manage().window().setSize(new Dimension(1296, 688));
    // 3 | runScript | window.scrollTo(0,137.3333282470703) | 
    js.executeScript("window.scrollTo(0,137.3333282470703)");
    // 4 | click | css=.\_588b5_3MtNs:nth-child(4) .bbe45_3oExY:nth-child(2) section:nth-child(2) | 
    driver.findElement(By.cssSelector(".\\_588b5_3MtNs:nth-child(4) .bbe45_3oExY:nth-child(2) section:nth-child(2)")).click();
    // 5 | close |  | 
    driver.close();
  }
  @Test
  public void usingthebuynowfunction() {
    // Test name: Using the buy now function
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("https://www.konga.com/");
    // 2 | setWindowSize | 1296x688 | 
    driver.manage().window().setSize(new Dimension(1296, 688));
    // 3 | click | linkText=Phones and Tablets | 
    driver.findElement(By.linkText("Phones and Tablets")).click();
    // 4 | click | css=.ea071_1Hjrs | 
    driver.findElement(By.cssSelector(".ea071_1Hjrs")).click();
    // 5 | runScript | window.scrollTo(0,298.6666564941406) | 
    js.executeScript("window.scrollTo(0,298.6666564941406)");
    // 6 | click | css=.bbe45_3oExY:nth-child(1) h3 | 
    driver.findElement(By.cssSelector(".bbe45_3oExY:nth-child(1) h3")).click();
    // 7 | runScript | window.scrollTo(0,122) | 
    js.executeScript("window.scrollTo(0,122)");
    // 8 | click | css=.\_7bc9f_Ef1Zw .\_0a08a_3czMG | 
    driver.findElement(By.cssSelector(".\\_7bc9f_Ef1Zw .\\_0a08a_3czMG")).click();
    // 9 | runScript | window.scrollTo(0,374) | 
    js.executeScript("window.scrollTo(0,374)");
    // 10 | close |  | 
    driver.close();
  }
  @Test
  public void removingitemfromcart() {
    // Test name: Removing item from cart
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("https://www.konga.com/");
    // 2 | setWindowSize | 1296x688 | 
    driver.manage().window().setSize(new Dimension(1296, 688));
    // 3 | click | css=.\_79484_1sLEt > span:nth-child(2) | 
    driver.findElement(By.cssSelector(".\\_79484_1sLEt > span:nth-child(2)")).click();
    // 4 | click | css=.bdb7c_1Gj3C:nth-child(1) button:nth-child(1) > span | 
    driver.findElement(By.cssSelector(".bdb7c_1Gj3C:nth-child(1) button:nth-child(1) > span")).click();
    // 5 | mouseOver | css=button:nth-child(1) > span | 
    {
      WebElement element = driver.findElement(By.cssSelector("button:nth-child(1) > span"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 6 | mouseOut | css=button:nth-child(1) > span | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 7 | click | css=.baac4_25nec svg | 
    driver.findElement(By.cssSelector(".baac4_25nec svg")).click();
    // 8 | close |  | 
    driver.close();
  }
  @Test
  public void checkCartitems() {
    // Test name: Check Cart items
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("https://www.konga.com/");
    // 2 | setWindowSize | 1296x688 | 
    driver.manage().window().setSize(new Dimension(1296, 688));
    // 3 | click | css=.\_79484_1sLEt | 
    driver.findElement(By.cssSelector(".\\_79484_1sLEt")).click();
    // 4 | click | css=.b6c6f_2H5Pm > path | 
    driver.findElement(By.cssSelector(".b6c6f_2H5Pm > path")).click();
    // 5 | close |  | 
    driver.close();
  }
  @Test
  public void kongaHealthFeature() {
    // Test name: Konga Health Feature
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("https://www.konga.com/");
    // 2 | setWindowSize | 1296x688 | 
    driver.manage().window().setSize(new Dimension(1296, 688));
    // 3 | click | css=.\_41783_2ijjb:nth-child(4) .f5e10_VzEXF | 
    vars.put("window_handles", driver.getWindowHandles());
    // 4 | storeWindowHandle | root | 
    driver.findElement(By.cssSelector(".\\_41783_2ijjb:nth-child(4) .f5e10_VzEXF")).click();
    // 5 | selectWindow | handle=${win8741} | 
    vars.put("win8741", waitForWindow(2000));
    // 6 | click | css=.b6c6f_2H5Pm | 
    vars.put("root", driver.getWindowHandle());
    // 7 | close |  | 
    driver.switchTo().window(vars.get("win8741").toString());
    // 8 | selectWindow | handle=${root} | 
    driver.findElement(By.cssSelector(".b6c6f_2H5Pm")).click();
    driver.close();
    driver.switchTo().window(vars.get("root").toString());
  }
  @Test
  public void kongaLogisticslink() {
    // Test name: Konga Logistics link
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("https://www.konga.com/");
    // 2 | setWindowSize | 1296x688 | 
    driver.manage().window().setSize(new Dimension(1296, 688));
    // 3 | click | css=.\_41783_2ijjb:nth-child(5) .f5e10_VzEXF | 
    vars.put("window_handles", driver.getWindowHandles());
    // 4 | storeWindowHandle | root | 
    driver.findElement(By.cssSelector(".\\_41783_2ijjb:nth-child(5) .f5e10_VzEXF")).click();
    // 5 | selectWindow | handle=${win9551} | 
    vars.put("win9551", waitForWindow(2000));
    // 6 | close |  | 
    vars.put("root", driver.getWindowHandle());
    // 7 | selectWindow | handle=${root} | 
    driver.switchTo().window(vars.get("win9551").toString());
    // 8 | close |  | 
    driver.close();
    driver.switchTo().window(vars.get("root").toString());
    driver.close();
  }
  @Test
  public void sellonKongafunction() {
    // Test name: Sell on Konga function
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("https://www.konga.com/");
    // 2 | setWindowSize | 1296x688 | 
    driver.manage().window().setSize(new Dimension(1296, 688));
    // 3 | click | linkText=Sell on Konga | 
    driver.findElement(By.linkText("Sell on Konga")).click();
    // 4 | click | linkText=Register Now | 
    vars.put("window_handles", driver.getWindowHandles());
    // 5 | storeWindowHandle | root | 
    driver.findElement(By.linkText("Register Now")).click();
    // 6 | selectWindow | handle=${win6954} | 
    vars.put("win6954", waitForWindow(2000));
    // 7 | close |  | 
    vars.put("root", driver.getWindowHandle());
    // 8 | selectWindow | handle=${root} | 
    driver.switchTo().window(vars.get("win6954").toString());
    // 9 | close |  | 
    driver.close();
    driver.switchTo().window(vars.get("root").toString());
    driver.close();
  }
  @Test
  public void trackingorder() {
    // Test name: Tracking order
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("https://www.konga.com/");
    // 2 | setWindowSize | 1296x688 | 
    driver.manage().window().setSize(new Dimension(1296, 688));
    // 3 | click | linkText=Track My Order | 
    vars.put("window_handles", driver.getWindowHandles());
    // 4 | storeWindowHandle | root | 
    driver.findElement(By.linkText("Track My Order")).click();
    // 5 | selectWindow | handle=${win5926} | 
    vars.put("win5926", waitForWindow(2000));
    // 6 | close |  | 
    vars.put("root", driver.getWindowHandle());
    // 7 | selectWindow | handle=${root} | 
    driver.switchTo().window(vars.get("win5926").toString());
    // 8 | close |  | 
    driver.close();
    driver.switchTo().window(vars.get("root").toString());
    driver.close();
  }
  @Test
  public void contactusfunction() {
    // Test name: contact us function
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("https://www.konga.com/");
    // 2 | setWindowSize | 1296x688 | 
    driver.manage().window().setSize(new Dimension(1296, 688));
    // 3 | click | linkText=Contact Us | 
    driver.findElement(By.linkText("Contact Us")).click();
    // 4 | runScript | window.scrollTo(0,146.6666717529297) | 
    js.executeScript("window.scrollTo(0,146.6666717529297)");
    // 5 | click | css=.b6c6f_2H5Pm | 
    driver.findElement(By.cssSelector(".b6c6f_2H5Pm")).click();
    // 6 | close |  | 
    driver.close();
  }
}
